name: Build and Deploy

on:
    push:
      branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Build with Maven
      run: mvn package -Dmaven.test.skip=true -Drun.profiles=prd --file pom.xml

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [build]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }} 
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Build Docker image
        run: docker build -f Dockerfile -t $REPO:$(date +%s) .
      - name: Publish Docker image
        run: docker push $REPO:$(date +%s)
